apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-event-app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: my-app-container
          image: navneethkrishna23/event:0.0.1
          ports:
            - containerPort: 5000